// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoEcJnF1R4n147fcdTYFfcz5By-5BeHT8',
    appId: '1:778638716966:web:c339f3efee5bc9530676e7',
    messagingSenderId: '778638716966',
    projectId: 'e-learning-app-d82a2',
    authDomain: 'e-learning-app-d82a2.firebaseapp.com',
    storageBucket: 'e-learning-app-d82a2.firebasestorage.app',
    measurementId: 'G-P00GDMY38D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzB2tUunn4HTFUWg0Eku7cK_UdWsuE2g4',
    appId: '1:778638716966:android:c3071c90e3f91aad0676e7',
    messagingSenderId: '778638716966',
    projectId: 'e-learning-app-d82a2',
    storageBucket: 'e-learning-app-d82a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-LYiaD-W5UwG_IBeoPAAzb1xMx0ejpws',
    appId: '1:778638716966:ios:65144d884c3544e90676e7',
    messagingSenderId: '778638716966',
    projectId: 'e-learning-app-d82a2',
    storageBucket: 'e-learning-app-d82a2.firebasestorage.app',
    androidClientId: '778638716966-sa6kklkod6l3a3uadlci4et0hd7ll4rq.apps.googleusercontent.com',
    iosClientId: '778638716966-iiobtrouv71qq6g031t2omf1uacje1mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-LYiaD-W5UwG_IBeoPAAzb1xMx0ejpws',
    appId: '1:778638716966:ios:65144d884c3544e90676e7',
    messagingSenderId: '778638716966',
    projectId: 'e-learning-app-d82a2',
    storageBucket: 'e-learning-app-d82a2.firebasestorage.app',
    androidClientId: '778638716966-sa6kklkod6l3a3uadlci4et0hd7ll4rq.apps.googleusercontent.com',
    iosClientId: '778638716966-iiobtrouv71qq6g031t2omf1uacje1mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoEcJnF1R4n147fcdTYFfcz5By-5BeHT8',
    appId: '1:778638716966:web:8e0b43b8aea8aee50676e7',
    messagingSenderId: '778638716966',
    projectId: 'e-learning-app-d82a2',
    authDomain: 'e-learning-app-d82a2.firebaseapp.com',
    storageBucket: 'e-learning-app-d82a2.firebasestorage.app',
    measurementId: 'G-FJFZRL7L3Y',
  );
}
